name: task_manager_apex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  hive: ^2.2.3
  json_annotation: ^4.9.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.6.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
